// Generated by Wrangler by running `wrangler types`
// Extended with project-specific environment variables
//
// POCKETBASE_SUPER_TOKEN is set via `wrangler secret put` in production
// and `dev.vars` in development. The Wrangler types generator only
// emits entries from wrangler.jsonc `vars`, so we add it here by hand.

interface Env {
	VALUE_FROM_CLOUDFLARE: "Hello from Cloudflare";
	POCKETBASE_URL: string;
	POCKETBASE_ADMIN_EMAIL: string;
	POCKETBASE_ADMIN_PASSWORD: string;
	POCKETBASE_SUPER_TOKEN: string;
	ALLOWED_ORIGINS: string;
	APP_URL?: string;
	SENTRY_DSN?: string;
}
