// Generated by Wrangler by running `wrangler types`
// Extended with project-specific environment variables

interface Env {
	VALUE_FROM_CLOUDFLARE: "Hello from Cloudflare";
	POCKETBASE_URL: string;
	POCKETBASE_ADMIN_EMAIL: string;
	POCKETBASE_ADMIN_PASSWORD: string;
	ALLOWED_ORIGINS: string;
}
